# Site settings
title: PoorlyWritten
description: "On Java, Unix, Programming and Craftsmanship"
baseurl: ""
url: ""
github_username:  olivergondza

# Build settings
markdown: kramdown

gems:
  - jekyll-feed
  - jekyll-seo-tag
